name: Create Debug Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create debug build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug

    - name: Set environment variables
      run: |
        echo "APK_PATH=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_ENV
        sha=`sha256sum ${{ env.APK_PATH }} | awk '{ print $1 }'`
        echo "APK_SHA256=$sha" >> $GITHUB_ENV

    - name: Get apk info
      id: apk-info
      uses: hkusu/apk-info-action@v1
      with:
        apk-path: ${{ env.APK_PATH }}

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v1
      with:
        body: "APK SHA-256 Checksum: ${{ env.APK_SHA256 }}"
        files: ${{ env.APK_PATH }}
        tag_name: ${{ steps.apk-info.outputs.version-name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LADB
        path: ${{ env.APK_PATH }}
